#!/bin/bash

echo "=== VeganMapAI Git Commit Script ==="
echo "Дата: January 8, 2025"
echo ""
echo "Следвайте тези стъпки за Git commit:"
echo ""
echo "1. Добавете всички промени:"
echo "   git add client/src/pages/landing.tsx"
echo "   git add test-map-public.html"
echo "   git add server/index.ts"
echo "   git add GIT-COMMIT-2025-08-08.md"
echo "   git add replit.md"
echo "   git add context/master.md"
echo "   git add api/openapi.yml"
echo "   git add docs/README.md"
echo "   git add .github/CODEOWNERS"
echo "   git add .github/pull_request_template.md"
echo "   git add .github/workflows/mirror-context.yml"
echo "   git add PROJECT-STRUCTURE-SUMMARY.md"
echo "   git add git-commit-instructions.sh"
echo ""
echo "2. Направете commit:"
echo "   git commit -m \"fix: Fixed landing page map button and added project structure\""
echo ""
echo "3. Push към repository (ако е настроен):"
echo "   git push origin main"
echo ""
echo "✅ Всичко е готово за Git commit!"
echo "✅ Нови папки: context/, api/, docs/"
echo "✅ Поправен бутон за публична карта"