#!/bin/bash

echo "=== VeganMapAI Git Commit Script ==="
echo "Дата: January 8, 2025"
echo ""
echo "Следвайте тези стъпки за Git commit:"
echo ""
echo "1. Добавете промените:"
echo "   git add client/src/pages/landing.tsx"
echo "   git add test-map-public.html"
echo "   git add server/index.ts"
echo "   git add GIT-COMMIT-2025-08-08.md"
echo "   git add replit.md"
echo "   git add git-commit-instructions.sh"
echo ""
echo "2. Направете commit:"
echo "   git commit -m \"fix: Fixed landing page map button and public map access\""
echo ""
echo "3. Push към repository (ако е настроен):"
echo "   git push origin main"
echo ""
echo "✅ Готово за Git commit!"