#!/bin/bash

echo "=== Test Mirror Workflow Script ==="
echo ""
echo "Стъпка 1: Добави тестовия файл"
echo "   git add context/test-trigger.txt"
echo ""
echo "Стъпка 2: Commit с тестово съобщение"
echo "   git commit -m 'test: trigger mirror workflow'"
echo ""
echo "Стъпка 3: Push към main branch"
echo "   git push origin main"
echo ""
echo "След теста:"
echo "   git rm context/test-trigger.txt"
echo "   git commit -m 'chore: remove test trigger file'"
echo "   git push origin main"
echo ""
echo "✅ Готово за тестване на GitHub Actions workflow!"