#!/bin/bash

echo "🔍 Алтернативен начин за намиране на Production DATABASE_URL"
echo "========================================================="
echo ""
echo "Ако не можете да намерите DATABASE_URL в Deployments,"
echo "опитайте следното:"
echo ""
echo "1. Отворете Neon Dashboard:"
echo "   https://console.neon.tech"
echo ""
echo "2. Влезте с вашия акаунт"
echo ""
echo "3. Намерете проекта 'VeganMapAI' или подобен"
echo ""
echo "4. Кликнете на 'Connection Details' или 'Dashboard'"
echo ""
echo "5. Копирайте 'Connection string' или 'DATABASE_URL'"
echo ""
echo "След като имате URL-а, изпълнете:"
echo ""
echo "DATABASE_URL='вашият-url' tsx import-production-fix.ts"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Или може да опитате с локалната база временно:"
echo "tsx import-restaurants.ts"
echo ""
echo "Но това няма да реши production проблема!"